# Generated by Django 4.2.2 on 2023-06-30 14:21

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(blank=True, upload_to='CategoryIcon', validators=[category.models.validate_image_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
